version: '3.8'
services:
  php:
    build:
      context: ./php-app
      dockerfile: Dockerfile
    container_name: php-container
    ports:
      - "8080:80"
    networks:
      - my-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
